---
title: Sneeuwpop
hero_image: images/banner.png
description: Bouw een 3D-model van een sneeuwpop met Blender
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-01-28
steps:
- title: Inleiding
- title: Onderkant van de sneeuwpop
- title: Hoofd van de sneeuwpop
  completion:
  - engaged
- title: Neus van de sneeuwpop
- title: Hoed van de sneeuwpop
  completion:
  - internal
- title: 'Uitdaging: ogen, armen en knopen'
