title: Snowman
hero_image: images/banner.png
description: Build a 3D model of a snowman using Blender
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-01-28
steps: 
- title: Introduction
- title: "Snowman's bottom"
- title: "Snowman's head"
- title: "Snowman's nose"
- title: "Snowman's hat"
- title: "Challenge: eyes, arms, and buttons"
