---
title: Schneemann
hero_image: images/banner.png
description: Baue ein 3D-Modell eines Schneemannes mit Blender
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-01-28
steps:
- title: Einleitung
- title: Schneemann Unterteil
- title: Schneemann Kopf
  completion:
  - engaged
- title: Schneemann Nase
- title: Schneemann Hut
  completion:
  - internal