---
title: Schneemann
hero_image: images/banner.png
description: Baue ein 3D-Modell eines Schneemannes mit Blender
theme: rot #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: Kunst
technologies: blender
site_areas: Projekte
hardware: ''
software: Blender
version: 4
last_tested: 2020-01-28
steps:
  - 
    title: Einführung
  - 
    title: "Schneemann Unterteil"
  - 
    title: "Schneemann Kopf"
  - 
    title: "Schneemann Nase"
  - 
    title: "Schneemann Hut"
  - 
    title: "Herausforderung: Augen, Arme und Knöpfe"
