---
title: Muñeco de nieve
hero_image: images/banner.png
description: Construye un modelo 3D de un muñeco de nieve usando Blender
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-01-28
steps:
  - 
    title: Introducción
  - 
    title: "La base del muñeco de nieve"
  - 
    title: "La cabeza del muñeco de nieve"
  - 
    title: "La nariz del muñeco de nieve"
  - 
    title: "El sombrero del muñeco de nieve"
  - 
    title: "Desafío: ojos, brazos y botones"
